#!/bin/bash

OUTPUT="$(jq -Mn \
    --arg access_key_id "${AWS_ACCESS_KEY_ID}" \
    --arg secret_access_key "${AWS_SECRET_ACCESS_KEY}" \
    --arg session_token "${AWS_SESSION_TOKEN}" \
    --arg security_token "${AWS_SECURITY_TOKEN}" \
    --arg expiration_date "$(date -v+10M -u "+%FT%TZ")" \
    '{Version: 1, AccessKeyId: $access_key_id, SecretAccessKey: $secret_access_key, SessionToken: $session_token, Expiration: $expiration_date}')"
if [ -z "$AWS_SESSION_TOKEN" ]; then
    OUTPUT="$(echo "$OUTPUT" | jq 'del(.Expiration)')"
fi
echo "$OUTPUT"