#!/bin/bash

set -eo pipefail

CMD="$1"

login()
{
    if [ -n "${AWS_PROFILE:-}" ]; then
        echo "ECR login in progress"
        $(aws ecr get-login --no-include-email)
    fi

    if [ -n "${DOCKER_USER:-}" ] && [ -n "${DOCKER_PASS:-}" ] ; then
        echo "Dockerhub login in progress"
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    fi

    if [ -n "${GITHUB_USERNAME:-}" ] && [ -n "${GITHUB_TOKEN:-}" ] ; then
        echo "Github login in progress"
        docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
    fi
}

case $CMD in
    build)
        REPO="$2"
        BUILD_PATH="$3"

        # Logic to determine the BRANCH tag
        if [ -n "$4" ]; then
            BRANCH=`echo $4 | sed 's/[\+\/]/-/g'`
        else
            BRANCH=`echo $(git rev-parse --symbolic-full-name --abbrev-ref HEAD) | sed 's/[\+\/]/-/g'`
        fi

        # Logic to determine the COMMIT tag
        if [ -n "$5" ]; then
            COMMIT="$5"
        elif [ -n "${CIRCLE_SHA1:-}" ]; then
            COMMIT="${CIRCLE_SHA1}"
        elif [ -n "${TRAVIS_COMMIT:-}" ]; then
            COMMIT="${TRAVIS_COMMIT}"
        else
            COMMIT=`git rev-parse --short HEAD`
        fi

        # Logic to determine the BUILD_NUMBER tag
        if [ -n "$6" ]; then
            BUILD_NUMBER="$6"
        elif [ -n "${CIRCLE_BUILD_NUM:-}" ]; then
            BUILD_NUMBER="${CIRCLE_BUILD_NUM}"
        elif [ -n "${TRAVIS_BUILD_NUMBER:-}" ]; then
            BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
        else
            BUILD_NUMBER="unknown"
        fi


        # Logic to determine the PROJ_NAME tag
        if [[ "$BUILD_PATH" == "." ]]; then
            PWD=$(pwd)
            PROJ_NAME=$(basename $PWD)
        else
            PROJ_NAME=$(basename $BUILD_PATH)
        fi


        PROJ_TAG="$REPO:$PROJ_NAME"
        GITHUB_REPO="docker.pkg.github.com/$REPO/$PROJ_NAME"

        login

        docker pull $PROJ_TAG || true
        docker build --cache-from $PROJ_TAG -t $PROJ_TAG "$BUILD_PATH"

        docker tag $PROJ_TAG $REPO:"sha-$COMMIT"
        docker tag $PROJ_TAG $REPO:"branch-$BRANCH"
        docker tag $PROJ_TAG $REPO:"build-$BUILD_NUMBER"
        docker tag $PROJ_TAG $REPO:"ci"
        echo "Tagged $PROJ_TAG with sha-$COMMIT, branch-$BRANCH, build-$BUILD_NUMBER, and ci"

        # if github credentials set, add github-specific tags
        if [ -n "${GITHUB_USERNAME:-}" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
            CI_TAG="$REPO:ci"
            docker tag $CI_TAG $GITHUB_REPO:"sha-$COMMIT"
            docker tag $CI_TAG $GITHUB_REPO:"branch-$BRANCH"
            echo "Tagged $CI_TAG with $GITHUB_REPO:sha-$COMMIT and $GITHUB_REPO:branch-$BRANCH"
        fi
    ;;
    push)
        REPO="$2"
        PROJ_NAME=$(basename $REPO)
        GITHUB_REPO="docker.pkg.github.com/$REPO/$PROJ_NAME"

        login

        # if dockerhub credentials set, push dockerhub
        if [ -n "${DOCKER_USER:-}" ] && [ -n "${DOCKER_PASS:-}" ]; then
            echo "Pushing to Dockerhub"
            docker push $REPO
        fi

        # if github credentials set, push to github
        if [ -n "${GITHUB_USERNAME:-}" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
            echo "Pushing to Github Package Registry"
            docker push $GITHUB_REPO
            if [ $? -ne 0 ]; then
                echo "Push to $GITHUB_REPO failed"
            fi
        fi

        # if aws_profile set, push to AWS
        if [ -n "${AWS_PROFILE:-}" ]; then
            echo "Pushing to ECR"
            docker push $REPO
            if [ $? -ne 0 ]; then
                echo "Push to AWS ECR failed. $REPO"
            fi
        fi
    ;;
    *)
        echo "Unknown command $CMD"
        exit 1
esac
