#!/bin/bash

set -euo pipefail

CMD="$1"

login()
{
    if [ -z "${AWS_PROFILE:-}" ]; then
        echo "Using Docker Hub login"
        if [ -z "${DOCKER_USER:-}" ] || [ -z "${DOCKER_PASS:-}" ]; then
            echo "Please set DOCKER_USER and DOCKER_PASS environment variables."
            exit 1
        fi
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    else
        echo "Using ECR login"
        $(aws ecr get-login --no-include-email)
    fi

    # Attempt to authenticate into github package registry
    echo "Authenticating on Github. Will peacefully exit if not set up yet."
    if [-z "$GITHUB_USERNAME"] || [-z "$GITHUB_TOKEN"]; then
        echo "No Github username or token set as environment variables"
    else
        docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
        if [$? -ne 0]; then
            echo "Authenticating to Github failed"
        fi
    fi
}

case $CMD in
    build)
        REPO="$2"
        BUILD_PATH="$3"
        BRANCH=`echo $4 | sed 's/[\+\/]/-/g'`
        COMMIT="$5"
        BUILD_NUMBER="$6"
        CI_TAG="$REPO:ci"
        PROJ_NAME=$(basename $REPO)
        GITHUB_REPO="docker.pkg.github.com/$REPO/$PROJ_NAME"


        login

        docker pull $CI_TAG || true
        docker build --cache-from $CI_TAG -t $CI_TAG "$BUILD_PATH"


        docker tag $CI_TAG $REPO:"sha-$COMMIT"
        docker tag $CI_TAG $REPO:"branch-$BRANCH"
        docker tag $CI_TAG $REPO:"build-$BUILD_NUMBER"
        docker tag $CI_TAG $GITHUB_REPO:"sha-$COMMIT"
        docker tag $CI_TAG $GITHUB_REPO:"branch-$BRANCH"
        docker tag $CI_TAG $GITHUB_REPO:"build-$BUILD_NUMBER"
    ;;
    push)
        # push to dockerhub
        REPO="$2"
        login
        docker push $REPO

        # attempt to push to github registry
        PROJ_NAME=$(basename $REPO)
        GITHUB_REPO="docker.pkg.github.com/$REPO/$PROJ_NAME"
        docker push $GITHUB_REPO
        if [ $? -ne 0 ]; then
            echo "Push to $GITHUB_REPO failed"
        fi
    ;;
    *)
        echo "Unknown command $CMD"
        exit 1
esac
